name: publish

on: push

permissions:
  contents: read
  packages: write

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, run, and push
        run: |
          IMAGE=ghcr.io/AxelG001/hello-docker-gcr-demo:latest
          docker build . --tag "$IMAGE"
          docker run --rm "$IMAGE"
          docker push "$IMAGE"
